import csv
import io
import json
import os
import sqlite3
from contextlib import contextmanager
from pathlib import Path

try:
    import psycopg2
    from psycopg2.extras import RealDictCursor
except Exception:  # pragma: no cover - optional until Postgres deps are installed
    psycopg2 = None
    RealDictCursor = None


SCHEMA = """
CREATE TABLE IF NOT EXISTS civilizations (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL UNIQUE,
    region TEXT,
    start_year INTEGER,
    end_year INTEGER,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS ledger_entries (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    civilization_id INTEGER NOT NULL REFERENCES civilizations(id) ON DELETE CASCADE,
    year INTEGER NOT NULL,
    entry_type TEXT NOT NULL CHECK (entry_type IN ('Asset', 'Liability')),
    domain TEXT NOT NULL CHECK (domain IN ('Economic', 'Military', 'Governance', 'Scientific', 'Social')),
    value REAL NOT NULL,
    description TEXT NOT NULL,
    source TEXT DEFAULT 'manual',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
"""


SQLITE_SCHEMA = SCHEMA.replace("INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY", "INTEGER PRIMARY KEY AUTOINCREMENT")


class LedgerDatabase:
    def __init__(self, database_url, sqlite_path):
        self.database_url = database_url
        self.sqlite_path = Path(sqlite_path)
        self.use_sqlite = not database_url or os.getenv("USE_SQLITE_FALLBACK", "true").lower() == "true"

    @contextmanager
    def connect(self):
        if not self.use_sqlite and psycopg2:
            conn = psycopg2.connect(self.database_url, cursor_factory=RealDictCursor)
        else:
            self.sqlite_path.parent.mkdir(parents=True, exist_ok=True)
            conn = sqlite3.connect(self.sqlite_path)
            conn.row_factory = sqlite3.Row
        try:
            yield conn
            conn.commit()
        finally:
            conn.close()

    def initialize(self):
        with self.connect() as conn:
            if self.use_sqlite:
                conn.executescript(SQLITE_SCHEMA)
            else:
                cur = conn.cursor()
                for statement in SCHEMA.split(";"):
                    if statement.strip():
                        cur.execute(statement)
        self.seed_if_empty()

    def seed_if_empty(self):
        if self.list_civilizations():
            return
        rome = self.register_civilization("Roman Empire", "Mediterranean", -27, 476, "Imperial Rome sample ledger.")
        maurya = self.register_civilization("Maurya Empire", "South Asia", -322, -185, "Ancient Indian imperial sample ledger.")
        self.add_ledger_entry(rome, 117, "Asset", "Military", 88, "The army secured frontier defenses and expanded imperial roads.", "seed")
        self.add_ledger_entry(rome, 180, "Liability", "Governance", 62, "Succession instability weakened administrative legitimacy.", "seed")
        self.add_ledger_entry(rome, 212, "Asset", "Social", 55, "Citizenship reforms widened political identity across provinces.", "seed")
        self.add_ledger_entry(maurya, -250, "Asset", "Governance", 82, "Ashoka promoted ethical rule, welfare officers, and public inscriptions.", "seed")
        self.add_ledger_entry(maurya, -260, "Liability", "Military", 48, "The Kalinga war caused severe human losses despite strategic victory.", "seed")
        self.add_ledger_entry(maurya, -240, "Asset", "Economic", 75, "Trade routes, taxation, and roads supported imperial integration.", "seed")

    def _placeholder(self):
        return "?" if self.use_sqlite else "%s"

    def _last_id(self, cursor):
        if self.use_sqlite:
            return cursor.lastrowid
        return cursor.fetchone()["id"]

    def register_civilization(self, name, region="", start_year=None, end_year=None, notes=""):
        ph = self._placeholder()
        with self.connect() as conn:
            cur = conn.cursor()
            if self.use_sqlite:
                cur.execute(
                    f"INSERT OR IGNORE INTO civilizations(name, region, start_year, end_year, notes) VALUES ({ph},{ph},{ph},{ph},{ph})",
                    (name, region, start_year, end_year, notes),
                )
                cur.execute(f"SELECT id FROM civilizations WHERE name={ph}", (name,))
                return dict(cur.fetchone())["id"]
            cur.execute(
                "INSERT INTO civilizations(name, region, start_year, end_year, notes) VALUES (%s,%s,%s,%s,%s) "
                "ON CONFLICT(name) DO UPDATE SET region=EXCLUDED.region RETURNING id",
                (name, region, start_year, end_year, notes),
            )
            return self._last_id(cur)

    def add_ledger_entry(self, civilization_id, year, entry_type, domain, value, description, source="manual"):
        ph = self._placeholder()
        with self.connect() as conn:
            cur = conn.cursor()
            returning = "" if self.use_sqlite else " RETURNING id"
            cur.execute(
                f"INSERT INTO ledger_entries(civilization_id, year, entry_type, domain, value, description, source) "
                f"VALUES ({ph},{ph},{ph},{ph},{ph},{ph},{ph}){returning}",
                (civilization_id, year, entry_type, domain, value, description, source),
            )
            return self._last_id(cur)

    def list_civilizations(self):
        with self.connect() as conn:
            cur = conn.cursor()
            cur.execute("SELECT * FROM civilizations ORDER BY name")
            return [dict(row) for row in cur.fetchall()]

    def list_ledger_entries(self, civilization_id=None):
        ph = self._placeholder()
        with self.connect() as conn:
            cur = conn.cursor()
            if civilization_id:
                cur.execute(
                    f"SELECT le.*, c.name AS civilization_name FROM ledger_entries le "
                    f"JOIN civilizations c ON c.id = le.civilization_id WHERE civilization_id={ph} ORDER BY year",
                    (civilization_id,),
                )
            else:
                cur.execute(
                    "SELECT le.*, c.name AS civilization_name FROM ledger_entries le "
                    "JOIN civilizations c ON c.id = le.civilization_id ORDER BY c.name, year"
                )
            return [dict(row) for row in cur.fetchall()]

    def import_csv_or_json(self, filename, stream):
        text = stream.read().decode("utf-8")
        rows = json.loads(text) if filename.lower().endswith(".json") else list(csv.DictReader(io.StringIO(text)))
        count = 0
        for row in rows:
            civ_name = row.get("civilization") or row.get("civilization_name") or row.get("name")
            if not civ_name:
                continue
            civ_id = self.register_civilization(
                civ_name,
                row.get("region", ""),
                _int_or_none(row.get("start_year")),
                _int_or_none(row.get("end_year")),
                row.get("notes", ""),
            )
            self.add_ledger_entry(
                civ_id,
                int(row.get("year", 0)),
                row.get("entry_type") or row.get("type") or "Asset",
                row.get("domain", "Social"),
                float(row.get("value", 50)),
                row.get("description", ""),
                row.get("source", filename),
            )
            count += 1
        return count


def _int_or_none(value):
    return None if value in (None, "") else int(value)
